@startuml

actor Fool1 #red
boundary Fool2 #blue
control Fool3
entity Fool4
database Fool5
collections Fool6


Fool1 -> Fool2 : To Boundary
Fool1 -> Fool3 : To Control
Fool1 -> Fool4 : To Entity
Fool1 -> Fool5 : To Database
Fool1 -> Fool6 : To Collections

@enduml

